"""Meldungen der API in den vier Oberflächensprachen.

Die Oberfläche schickt ihre Sprache im Kopf „X-Sprache“. Ohne Kopf bleibt es bei Deutsch, so
bleiben Tests und Skripte unverändert. Schlüssel statt Sätze im Code, damit nichts vergessen wird.
"""
from __future__ import annotations

from . import config

TEXTE: dict[str, dict[str, str]] = {
    "de": {
        "anmelden_fehlt": "Bitte zuerst anmelden.",
        "nur_admin": "Nur für Admins.",
        "login_falsch": "E-Mail-Adresse oder Passwort stimmt nicht.",
        "gesperrt": "Zu viele Fehlversuche. Bitte in {min} Minuten erneut versuchen.",
        "gesperrt_einmal": "Zu viele Fehlversuche. Bitte in {min} Minuten erneut versuchen, oder der Admin vergibt ein neues Einmal-Passwort.",
        "erst_noetig": "Dieses Konto ist noch nicht eingerichtet. Bitte die Erstanmeldung mit dem Einmal-Passwort nutzen.",
        "name_laenge": "Der Name braucht 2 bis 80 Zeichen.",
        "einmal_falsch": "E-Mail-Adresse oder Einmal-Passwort stimmt nicht, oder das Einmal-Passwort ist abgelaufen.",
        "code_falsch": "Der Code stimmt nicht oder ist abgelaufen.",
        "name_fehlt": "Bitte einen Namen eingeben.",
        "pwd_regel": "Das Passwort erfüllt die Regel nicht.",
        "pwd_ungleich": "Die beiden Passwörter stimmen nicht überein.",
        "einstellung_ungueltig": "Diese Einstellung gibt es nicht oder der Wert ist nicht erlaubt.",
        "punkte_liste": "Bitte eine Liste von Prüfpunkt-IDs senden.",
        "punkt_unbekannt": "Unbekannter Prüfpunkt: {ids}.",
        "punkt_unbekannt_satz": "Unbekannter Prüfpunkt für die gewählten Regelsätze: {ids}.",
        "satz_leer": "Regelsatz {satz} hat keinen aktiven Prüfpunkt. Regelsatz abwählen oder Punkte einschalten.",
        "pwd_alt_falsch": "Das bisherige Passwort stimmt nicht.",
        "pwd_neu_regel": "Das neue Passwort erfüllt die Regel nicht.",
        "inhaber_schutz": "Das Inhaber-Konto kann nur der Inhaber selbst ändern.",
        "email_ungueltig": "Bitte eine gültige E-Mail-Adresse eingeben.",
        "rolle_ungueltig": "Rolle muss admin oder mitglied sein.",
        "email_vergeben": "Diese E-Mail-Adresse hat schon ein Konto.",
        "konto_fehlt": "Konto nicht gefunden.",
        "admin_selbst": "Du kannst dir selbst die Admin-Rolle nicht entziehen.",
        "sperren_selbst": "Du kannst dich nicht selbst sperren.",
        "loeschen_inhaber": "Konten löschen darf nur der Inhaber.",
        "loeschen_selbst": "Du kannst dein eigenes Konto nicht löschen.",
        "pruefung_fehlt": "Prüfung nicht gefunden.",
        "lauf_fehlt": "Prüflauf nicht gefunden.",
        "bericht_fehlt": "Bericht nicht gefunden.",
        "bericht_sprache": "Für diese Sprache wurde bei der Prüfung kein Bericht gewählt.",
        "zu_viele_dateien": "Höchstens {n} Dateien je Prüfung.",
        "dateityp": "{name}: Nur Word (.docx) und PDF (.pdf) werden geprüft.",
        "zu_gross": "{name} ist größer als 25 MB.",
        "regelsaetze_ungueltig": "Bitte gültige Regelsätze wählen: basis, din oder ce.",
        "sprachen_ungueltig": "Bitte eine oder zwei Berichtssprachen wählen: de, en, uk, ru.",
        "pruefung_fehlgeschlagen": "Die Prüfung ist fehlgeschlagen. Bitte noch einmal versuchen.",
        "lesen_docx_oeffnen": "Die Word-Datei lässt sich nicht öffnen. Vermutlich beschädigt oder kein echtes .docx.",
        "lesen_docx_inhalt": "Der Inhalt der Word-Datei lässt sich nicht lesen. Vermutlich beschädigt.",
        "lesen_pdf_oeffnen": "Die PDF-Datei lässt sich nicht öffnen. Vermutlich beschädigt oder verschlüsselt.",
        "lesen_kein_text": "Keine Textinhalte erkannt.",
        "lesen_kein_text_scan": "Keine Textinhalte erkannt. Vermutlich ein Scan ohne Textebene.",
        "lesen_dateityp": "Nur Word (.docx) und PDF (.pdf) werden geprüft.",
    },
    "en": {
        "anmelden_fehlt": "Please sign in first.",
        "nur_admin": "Admins only.",
        "login_falsch": "E-mail address or password is incorrect.",
        "gesperrt": "Too many failed attempts. Please try again in {min} minutes.",
        "gesperrt_einmal": "Too many failed attempts. Please try again in {min} minutes, or ask the admin for a new one-time password.",
        "erst_noetig": "This account is not set up yet. Please use the first sign-in with the one-time password.",
        "name_laenge": "The name needs 2 to 80 characters.",
        "einmal_falsch": "E-mail address or one-time password is incorrect, or the one-time password has expired.",
        "code_falsch": "The code is incorrect or has expired.",
        "name_fehlt": "Please enter a name.",
        "pwd_regel": "The password does not meet the rule.",
        "pwd_ungleich": "The two passwords do not match.",
        "einstellung_ungueltig": "This setting does not exist or the value is not allowed.",
        "punkte_liste": "Please send a list of check point IDs.",
        "punkt_unbekannt": "Unknown check point: {ids}.",
        "punkt_unbekannt_satz": "Unknown check point for the selected rule sets: {ids}.",
        "satz_leer": "Rule set {satz} has no active check point. Deselect the rule set or enable points.",
        "pwd_alt_falsch": "The current password is incorrect.",
        "pwd_neu_regel": "The new password does not meet the rule.",
        "inhaber_schutz": "Only the owner can change the owner account.",
        "email_ungueltig": "Please enter a valid e-mail address.",
        "rolle_ungueltig": "Role must be admin or member.",
        "email_vergeben": "This e-mail address already has an account.",
        "konto_fehlt": "Account not found.",
        "admin_selbst": "You cannot remove your own admin role.",
        "sperren_selbst": "You cannot lock yourself.",
        "loeschen_inhaber": "Only the owner can delete accounts.",
        "loeschen_selbst": "You cannot delete your own account.",
        "pruefung_fehlt": "Check not found.",
        "lauf_fehlt": "Check run not found.",
        "bericht_fehlt": "Report not found.",
        "bericht_sprache": "No report was selected in this language for this check.",
        "zu_viele_dateien": "At most {n} files per check.",
        "dateityp": "{name}: Only Word (.docx) and PDF (.pdf) are checked.",
        "zu_gross": "{name} is larger than 25 MB.",
        "regelsaetze_ungueltig": "Please choose valid rule sets: basis, din or ce.",
        "sprachen_ungueltig": "Please choose one or two report languages: de, en, uk, ru.",
        "pruefung_fehlgeschlagen": "The check failed. Please try again.",
        "lesen_docx_oeffnen": "The Word file cannot be opened. Probably damaged or not a real .docx.",
        "lesen_docx_inhalt": "The content of the Word file cannot be read. Probably damaged.",
        "lesen_pdf_oeffnen": "The PDF file cannot be opened. Probably damaged or encrypted.",
        "lesen_kein_text": "No text content found.",
        "lesen_kein_text_scan": "No text content found. Probably a scan without a text layer.",
        "lesen_dateityp": "Only Word (.docx) and PDF (.pdf) are checked.",
    },
    "uk": {
        "anmelden_fehlt": "Спочатку увійдіть.",
        "nur_admin": "Лише для адміністраторів.",
        "login_falsch": "Неправильна адреса електронної пошти або пароль.",
        "gesperrt": "Забагато невдалих спроб. Спробуйте ще раз через {min} хв.",
        "gesperrt_einmal": "Забагато невдалих спроб. Спробуйте ще раз через {min} хв або попросіть адміністратора видати новий одноразовий пароль.",
        "erst_noetig": "Цей обліковий запис ще не налаштовано. Скористайтеся першим входом з одноразовим паролем.",
        "name_laenge": "Ім’я має містити від 2 до 80 символів.",
        "einmal_falsch": "Неправильна адреса електронної пошти або одноразовий пароль, або термін дії одноразового пароля минув.",
        "code_falsch": "Код неправильний або його термін дії минув.",
        "name_fehlt": "Введіть ім’я.",
        "pwd_regel": "Пароль не відповідає правилу.",
        "pwd_ungleich": "Паролі не збігаються.",
        "einstellung_ungueltig": "Такого налаштування немає або значення не дозволене.",
        "punkte_liste": "Надішліть список ідентифікаторів пунктів перевірки.",
        "punkt_unbekannt": "Невідомий пункт перевірки: {ids}.",
        "punkt_unbekannt_satz": "Невідомий пункт перевірки для вибраних наборів правил: {ids}.",
        "satz_leer": "Набір правил {satz} не має жодного активного пункту. Зніміть вибір набору або увімкніть пункти.",
        "pwd_alt_falsch": "Поточний пароль неправильний.",
        "pwd_neu_regel": "Новий пароль не відповідає правилу.",
        "inhaber_schutz": "Обліковий запис власника може змінювати лише сам власник.",
        "email_ungueltig": "Введіть дійсну адресу електронної пошти.",
        "rolle_ungueltig": "Роль має бути admin або mitglied.",
        "email_vergeben": "Для цієї адреси вже є обліковий запис.",
        "konto_fehlt": "Обліковий запис не знайдено.",
        "admin_selbst": "Ви не можете зняти з себе роль адміністратора.",
        "sperren_selbst": "Ви не можете заблокувати себе.",
        "loeschen_inhaber": "Видаляти облікові записи може лише власник.",
        "loeschen_selbst": "Ви не можете видалити власний обліковий запис.",
        "pruefung_fehlt": "Перевірку не знайдено.",
        "lauf_fehlt": "Серію перевірок не знайдено.",
        "bericht_fehlt": "Звіт не знайдено.",
        "bericht_sprache": "Для цієї мови під час перевірки звіт не обирався.",
        "zu_viele_dateien": "Не більше {n} файлів за одну перевірку.",
        "dateityp": "{name}: перевіряються лише Word (.docx) і PDF (.pdf).",
        "zu_gross": "{name} більший за 25 МБ.",
        "regelsaetze_ungueltig": "Виберіть дійсні набори правил: basis, din або ce.",
        "sprachen_ungueltig": "Виберіть одну або дві мови звіту: de, en, uk, ru.",
        "pruefung_fehlgeschlagen": "Перевірка не вдалася. Спробуйте ще раз.",
        "lesen_docx_oeffnen": "Файл Word не відкривається. Ймовірно, пошкоджений або не справжній .docx.",
        "lesen_docx_inhalt": "Вміст файлу Word не читається. Ймовірно, пошкоджений.",
        "lesen_pdf_oeffnen": "Файл PDF не відкривається. Ймовірно, пошкоджений або зашифрований.",
        "lesen_kein_text": "Текст не розпізнано.",
        "lesen_kein_text_scan": "Текст не розпізнано. Ймовірно, скан без текстового шару.",
        "lesen_dateityp": "Перевіряються лише Word (.docx) і PDF (.pdf).",
    },
    "ru": {
        "anmelden_fehlt": "Сначала войдите.",
        "nur_admin": "Только для администраторов.",
        "login_falsch": "Неверный адрес электронной почты или пароль.",
        "gesperrt": "Слишком много неудачных попыток. Повторите через {min} мин.",
        "gesperrt_einmal": "Слишком много неудачных попыток. Повторите через {min} мин или попросите администратора выдать новый одноразовый пароль.",
        "erst_noetig": "Эта учётная запись ещё не настроена. Воспользуйтесь первым входом с одноразовым паролем.",
        "name_laenge": "Имя должно содержать от 2 до 80 символов.",
        "einmal_falsch": "Неверный адрес электронной почты или одноразовый пароль, либо срок действия одноразового пароля истёк.",
        "code_falsch": "Код неверный или его срок действия истёк.",
        "name_fehlt": "Введите имя.",
        "pwd_regel": "Пароль не соответствует правилу.",
        "pwd_ungleich": "Пароли не совпадают.",
        "einstellung_ungueltig": "Такой настройки нет или значение недопустимо.",
        "punkte_liste": "Отправьте список идентификаторов пунктов проверки.",
        "punkt_unbekannt": "Неизвестный пункт проверки: {ids}.",
        "punkt_unbekannt_satz": "Неизвестный пункт проверки для выбранных наборов правил: {ids}.",
        "satz_leer": "В наборе правил {satz} нет активных пунктов. Снимите выбор набора или включите пункты.",
        "pwd_alt_falsch": "Текущий пароль неверный.",
        "pwd_neu_regel": "Новый пароль не соответствует правилу.",
        "inhaber_schutz": "Учётную запись владельца может изменять только сам владелец.",
        "email_ungueltig": "Введите действительный адрес электронной почты.",
        "rolle_ungueltig": "Роль должна быть admin или mitglied.",
        "email_vergeben": "Для этого адреса уже есть учётная запись.",
        "konto_fehlt": "Учётная запись не найдена.",
        "admin_selbst": "Вы не можете снять с себя роль администратора.",
        "sperren_selbst": "Вы не можете заблокировать себя.",
        "loeschen_inhaber": "Удалять учётные записи может только владелец.",
        "loeschen_selbst": "Вы не можете удалить собственную учётную запись.",
        "pruefung_fehlt": "Проверка не найдена.",
        "lauf_fehlt": "Серия проверок не найдена.",
        "bericht_fehlt": "Отчёт не найден.",
        "bericht_sprache": "Для этого языка при проверке отчёт не выбирался.",
        "zu_viele_dateien": "Не более {n} файлов за одну проверку.",
        "dateityp": "{name}: проверяются только Word (.docx) и PDF (.pdf).",
        "zu_gross": "{name} больше 25 МБ.",
        "regelsaetze_ungueltig": "Выберите допустимые наборы правил: basis, din или ce.",
        "sprachen_ungueltig": "Выберите один или два языка отчёта: de, en, uk, ru.",
        "pruefung_fehlgeschlagen": "Проверка не удалась. Попробуйте ещё раз.",
        "lesen_docx_oeffnen": "Файл Word не открывается. Вероятно, повреждён или не настоящий .docx.",
        "lesen_docx_inhalt": "Содержимое файла Word не читается. Вероятно, повреждён.",
        "lesen_pdf_oeffnen": "Файл PDF не открывается. Вероятно, повреждён или зашифрован.",
        "lesen_kein_text": "Текст не распознан.",
        "lesen_kein_text_scan": "Текст не распознан. Вероятно, скан без текстового слоя.",
        "lesen_dateityp": "Проверяются только Word (.docx) и PDF (.pdf).",
    },
}


def sprache_aus(kopf: str | None) -> str:
    """Gültige Sprache aus dem Kopf X-Sprache, sonst Deutsch."""
    wert = (kopf or "").strip().lower()
    return wert if wert in config.SPRACHEN else "de"


def t(sprache: str, schluessel: str, **werte: object) -> str:
    tabelle = TEXTE.get(sprache) or TEXTE["de"]
    vorlage = tabelle.get(schluessel) or TEXTE["de"][schluessel]
    return vorlage.format(**werte) if werte else vorlage
